export const ADD_WORDS = 'ADD_WORDS';
export const RESET_GAME = 'RESET_GAME';
export const CREATE_TEXT = 'CREATE_TEXT';
export const FETCH_TEXT_START = 'FETCH_TEXT_START';
export const FETCH_TEXT_ERROR = 'FETCH_TEXT_ERROR';
export const FETCH_TEXT_RESPONSE = 'FETCH_TEXT_RESPONSE';

